name: Deploy VitePress to GitHub Pages
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史[2](@ref)

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.7.1  # 匹配您的packageManager版本[6](@ref)
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'  # 启用PNPM缓存加速[2](@ref)

      - name: Install dependencies
        run: |
             pnpm install --force
             pnpm rebuild  # 强制重建本地包链接

      - name: Build VitePress
        run: pnpm run docs:build

      - name: Add .nojekyll
        run: touch docs/.vitepress/dist/.nojekyll  # 防止忽略下划线文件[2,4](@ref)

      - name: Configure Pages
        uses: actions/configure-pages@v3  # 自动配置Pages[2](@ref)

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
